# Generated by Django 3.2.4 on 2021-08-31 11:45

from django.db import migrations, models
import hero_tour_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_tour_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='img',
            field=models.ImageField(default='', upload_to=hero_tour_app.models.upload_path),
        ),
        migrations.AlterField(
            model_name='hero',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
