# Generated by Django 3.2.4 on 2021-09-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero_tour_app', '0002_auto_20210831_1345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hero',
            new_name='HeroModel',
        ),
    ]
