# Generated by Django 3.2.7 on 2021-09-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_tour_app', '0005_auto_20210903_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(max_length=10)),
                ('desciption', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='HeroModel',
        ),
        migrations.DeleteModel(
            name='UserModel123',
        ),
    ]
