# Generated by Django 3.2.7 on 2021-09-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_tour_app', '0006_auto_20210923_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
